name: Tests

# Controls when the workflow will run
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: rbaltrusch/batest
          path: batest
      - uses: actions/checkout@v2
        with:
          repository: rbaltrusch/objectbatch
          path: objectbatch
      - name: Run tests
        working-directory: objectbatch/tests
        shell: cmd
        run: run_tests
