name: Tests

# Controls when the workflow will run
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5
        with:
          repository: rbaltrusch/batest
          path: batest
      - uses: actions/checkout@v5
        with:
          repository: rbaltrusch/objectbatch
          path: objectbatch
      - name: Run tests
        shell: cmd
        run: |
          call "objectbatch/tests/run_tests.bat"
