name: Tests

# Controls when the workflow will run
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: rbaltrusch/batest
          #path: batest
      - name: Run tests
        #working-directory: tests
        shell: cmd
        #run: run_tests
        run: tree /a
